server:
  port: 8084

spring:
  profiles: dev
  application:
    name: abcmsc-provider-depart



  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql:///test02?useUnicode=true&amp;characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://eureka8400.com:8400/eureka

#配置测试环境test
server:
  port: 8085

spring:
  profiles: test
  application:
    name: abcmsc-provider-depart

  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql:///test03?useUnicode=true&amp;characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://eureka8500.com:8500/eureka


