server:
  port: 7070

spring:
  profiles: dev
  application:
    name: abcmsc-consumer-depart
eureka:
  client:
    service-url:
      defaultZone: http://eureka8400.com:8400/eureka

feign:
  hystrix:
    enabled: true



server:
  port: 9090

spring:
  profiles: dev
  application:
    name: abcmsc-consumer-depart
eureka:
  client:
    service-url:
      defaultZone: http://eureka8500.com:8500/eureka

feign:
  hystrix:
    enabled: true
